# Generated by Django 3.1.5 on 2021-05-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_spacompound_crystal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacompound',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spacompound',
            name='library_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spacompound',
            name='library_plate',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spacompound',
            name='smiles',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='spacompound',
            name='visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spacompound',
            name='well',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
