# Generated by Django 3.1.5 on 2021-03-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20210310_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='compound',
        ),
        migrations.AddField(
            model_name='lab',
            name='crystal_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.crystal'),
        ),
    ]
