# Generated by Django 3.1.5 on 2021-06-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20210610_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crystal',
            name='crystal_plate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crystals', to='API.crystalplate'),
        ),
    ]
