# Generated by Django 3.1.5 on 2021-06-21 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_auto_20210611_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='solventbatch',
            name='visit',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='crystals', to='API.batch'),
        ),
    ]
