# Generated by Django 3.1.5 on 2021-06-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210621_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='compound_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_data', to='API.compoundcombination'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='single_compound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_data', to='API.spacompound'),
        ),
    ]
