# Generated by Django 3.1.5 on 2021-07-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20210626_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solventbatch',
            name='soak_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
