# Generated by Django 3.1.5 on 2021-07-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20210712_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solventbatch',
            old_name='soak_time',
            new_name='soak_timestamp',
        ),
    ]
