# Generated by Django 3.1.5 on 2021-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_auto_20210713_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='solventbatch',
            name='cryo_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solventbatch',
            name='soaking_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
